### ISSUE TITLE
Drop dead-end code

### ISSUE THREAD

**Issue by ajschult** [etomica/etomica#105]
There are a few packages that have code that happily compiles and was being developed at some point, but is unlikely to ever be useful to anyone in the future.  The primary effects at this point are:

- Make refactoring more tedious (sheer number of classes that must be fixed)
- Confuse people who don't know to divert their eyes
- Make us constantly wonder what people were thinking when they wrote the code

Prime examples are:

1. [etomica.models.hexane](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/models/hexane)
2. [etomica.models.oneDHardRods](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/models/oneDHardRods)
3. [etomica.paracetamol](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/paracetamol)

The projects corresponding to the above packages did not go anywhere and hexane and paracetamol never even got to the point that we believed the results.  There are additional classes sprinkled around, but those 3 packages are mostly easily identified as dead.

**Comment by ajschult** [comment]
Less obvious, but still might be in the same category

4. [etomica.modules.joulethomson](https://github.com/etomica/etomica/tree/master/etomica-modules/src/main/java/etomica/modules/joulethomson) and supporting code like [IntegratorGear4NPH](https://github.com/etomica/etomica/blob/master/etomica-core/src/main/java/etomica/integrator/IntegratorGear4NPH.java)
5. Random classes written by students as one-off projects, like IntegratorConNVT, IntegratorAnalytic
6. ~~[Rigid body integration](http://rheneas.eng.buffalo.edu/~andrew/rotation/title.xhtml); IntegratorRigidIterative, IntegratorRigidMatrixIterative and classes that use them.~~

**Comment by ajschult** [comment]
7. [etomica.simulation.prototypes.DemoSim](https://github.com/etomica/etomica/blob/master/etomica-core/src/main/java/etomica/simulation/prototypes/DemoSim.java)

**Comment by ajschult** [comment]
8. [etomica.modules.entropylottery](https://github.com/etomica/etomica/tree/master/etomica-modules/src/main/java/etomica/modules/entropylottery)

**Comment by akofke** [comment]
We should do this pretty liberally if we're planning on making big changes. We can keep a branch with legacy stuff on it so people can go back and run them if they want.

**Comment by akofke** [comment]
I thought the modules all had uses though?

**Comment by ajschult** [comment]
joulethomson was a very old module that I tried to revive and never got working.  entropylottery is one that I made (and it works), but it never got finished because the guy who came up with the idea lost interest.

**Comment by ajschult** [comment]
We're always making big changes.  :)  And we're going to keep making big changes until we decide to stop (probably sometime in the year 2098).  Even if we dump some of the stuff now, we may decide that other bits are dumpable in another year.  We can't really create a branch every time we notice something obsolete.

**Comment by akofke** [comment]
Well I was mostly thinking of the vector arrays replacing atoms changes. I mean at some point hopefully we'll not need to make big changes and can have [semantic versioning](https://semver.org/) releases. 

We wouldn't have to keep making branches, they'd already be on the old branch. It's the same as making a tag saying "here's the commit before we nuked everything", except having a branch makes it easier to back-port changes if necessary.

**Comment by ajschult** [comment]
9. parts of [etomica.meam](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/meam/) that are actually doing meam (and not eam, efs, etc.).  The meam code is fine, but it's so grossly inefficient (because it had to behave like an Etomica Potential) that nobody should use it.

**Comment by ajschult** [comment]
10. [etomica.yukawa](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/yukawa/)

**Comment by ajschult** [comment]
11. [etomica.thermointegration](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/thermointegration/) a demo for one of The API meetings
12. [etomica.threads](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/threads/) -- Alex already gutted this package.  I doubt the remaining bits are useful
13. [etomica.densityofstate](https://github.com/etomica/etomica/tree/master/etomica-apps/src/main/java/etomica/densityofstate/) not sure what this even does

**Comment by ajschult** [comment]
14. Everyone's favorite non-functional module, [etomica.modules.render](https://github.com/etomica/etomica/tree/master/etomica-modules/src/main/java/etomica/modules/render/)

**Comment by ajschult** [comment]
All done!

**Comment by akofke** [comment]
These can now all be found by checking out the [legacy-packages](https://github.com/etomica/etomica/releases/tag/legacy-packages) tag.
