### ISSUE TITLE
Windows Etomica Install LJMD

### ISSUE THREAD

**Issue by CalCraven** [etomica/etomica#140]
There seems to be an issue with the Windows install for the [most recent release of etomica](https://github.com/etomica/etomica/releases/tag/modules-nightly-7f43a28-2021-10-25). `Etomica-modules-Windows.zip`

The install worked okay, and the applets open once the etomica-modules.exe is opened. Once the popup is opened, you can select the application of your choice. For whatever reason, the **LJMD** application will not open. All others work okay, but when you hit launch for the LJMD option, nothing is opened.

Windows operating system 64-bit.

If you have further questions, let me know and I can try to get images of replication of the bug. It did not occur on my system though, so I would need to acquisition an undergraduate's laptop to replicate the bug in more detail.

**Comment by ajschult** [comment]
Thanks for the report.  LJMD was broken in the last release, but is working in our current code.  I've published a new release and LJMD should work fine there.

https://github.com/etomica/etomica/releases/tag/modules-nightly-3f39ed8-2021-11-16

**Comment by CalCraven** [comment]
Thanks for the release! That's some timely work 🥇
