### ISSUE TITLE
Add a way to get ActivityIntegrate to bail if some wallclock time reached

### ISSUE THREAD

**Issue by ajschult** [etomica/etomica#142]
I'm thinking of some way to get a simulation to bail if some time limit is reached.  To do this, ActivityIntegrate needs to stop after some time.  In the old world, I think we would have made an IntegratorListener that checks the time and sets maxSteps to 0 if the limit is reached (we had listeners that did this for other purposes, like "this simulation has accomplished what we need, let's stop").  We could do this, but it's pretty ugly, our more recent code has more ActivityIntegrates, and we typically have something like

controller.runActivityBlocking(new ActivityIntegrate);

with that style, there's no opportunity to give the ActivityIntergate to a listener.  And then if we call runActivityBlocking several times (for equilibration, then production, etc), it's even more complicated.

Instead, we could give a time limit to the ActivityIntegrate constructor and things would be a lot cleaner.  I'm not sure if we should give the time limit as:

1. Elapsed seconds
2. Elapsed nanoseconds (since we'll be calling System.nanoTime() to check anyway)
3. Return value of nanoTime() to stop
4. Something else?

Elapsed time seems more intuitive, but giving a final time to stop (#3) might be more useful in cases where we want the whole simulation to stop at some time and we invoke runActivityBlocking several times.  If we give elapsed time, then we need to (in the main method), recompute the max elapsed time each time it makes a new ActivityIntegrate.

**Comment by kofke** [comment]
An approach using the constructor would be appropriate.  You could select one way to specify the time limit (e.g., elapsed seconds) and provide static methods for convenience that take alternate inputs and convert to the required input form.

**Comment by ajschult** [comment]
I am a bit concerned about calling System.nanoTime() after every step.  For MC, that may cause a noticeable slowdown.  We could play games like (in order of fanciness):
1. checking after ~100th step (because a single step is never going to be substantial, whereas 100 steps should always be nontrivial) or 
2. checking time per step and adjusting the check interval so that we (for instance) check once per second or so
3. Using some external timer

I'd lean toward something like 1.

**Comment by ajschult** [comment]
Resolved
