### ISSUE TITLE
gradlew build fails on CentOS 7 workstations

### ISSUE THREAD

**Issue by ajschult** [etomica/etomica#29]
gradlew build works on fedora, but fails on our workstations (CentOS 7).  I installed python 3.4:

#which python3
/usr/bin/python3

But problems remain.  Output from gradlew build includes:

:setupPython
Error: Command '['/tmp/foo/etomica/etomica-core/src/main/resources/virtualenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
./setup_python.sh: line 11: etomica-core/src/main/resources/virtualenv/bin/activate: No such file or directory

things go downhill from there.  Also:

$ ls etomica-core/src/main/resources/virtualenv/
bin  include  lib  lib64  pyvenv.cfg
$ cd etomica-core/src/main/resources/virtualenv/
$ ls */
bin:
python  python3

include:

lib:
python3.4

lib64:
python3.4

**Comment by akofke** [comment]
I knew this python hackery would cause trouble eventually... looks like the virtualenv doesn't install completely. Google tells me that Debian/Ubuntu shipped a broken python 3.4 which did exactly that, although I didn't see anything about it happening on CentOS.

What happens if you replace it with python 3.5 or 3.6?
Also what's the output of `python3 -Im ensurepip -h` for good measure.

**Comment by akofke** [comment]
I'm trying it in virtualbox to see if I can reproduce

**Comment by akofke** [comment]
How did you install python3? I'm reading that some of the ways to install it on CentOS don't include pip and setuptools.

**Comment by ajschult** [comment]
Enable the EPEL repo (http://fedoraproject.org/wiki/EPEL) and then

yum install python34 python34-pip

python35 is available via software collections, but won't be quite as convenient to use.  'which python3' won't find it by default.

**Comment by ajschult** [comment]
There should be an epel-release package in CentOS Extras (enabled by default, I think), so you should be able to add EPEL via

yum install epel-release

**Comment by ajschult** [comment]
see
https://bugzilla.redhat.com/show_bug.cgi?id=1319963
https://bugzilla.redhat.com/show_bug.cgi?id=1263057

and
```bash
$ python3 -Im ensurepip -h
usage: python -m ensurepip [-h] [--version] [-v] [-U] [--user] [--root ROOT]
                           [--altinstall] [--default-pip]

optional arguments:
  -h, --help     show this help message and exit
  --version      Show the version of pip that is bundled with this Python.
  -v, --verbose  Give more output. Option is additive, and can be used up to 3
                 times.
  -U, --upgrade  Upgrade pip and dependencies, even if already installed.
  --user         Install using the user scheme.
  --root ROOT    Install everything relative to this alternate root directory.
  --altinstall   Make an alternate install, installing only the X.Y
                 versionedscripts (Default: pipX, pipX.Y, easy_install-X.Y)
  --default-pip  Make a default pip install, installing the unqualified pip
                 and easy_install in addition to the versioned scripts```

**Comment by akofke** [comment]
It's broken for me too using the EPEL python. From those bugzilla discussions it sounds like this is a bug in the distribution with no real solution, is there anything we can even do? 

I'll try to find a better way for bundling the python program, or make it skip those tests if the install script fails.

**Comment by akofke** [comment]
The python 3.5 from IUS (I read in the guide [here](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7)) works but it doesn't install a python3 executable, only python3.5. I could change the script to account for this if you think it's viable to install on all the workstations.

**Comment by ajschult** [comment]
I'll try python 3.5 from software collections.  We're already using SCL one one machine.

**Comment by ajschult** [comment]
python 3.5 from SCL works fine.  I'll install it on the workstations.
Next issue...

**Comment by ajschult** [comment]
I should add that it would be nice if building the python bits was optional and/or the build could skip python in environments with broken or missing python

**Comment by akofke** [comment]
Yeah that's how I'd like to do it but I haven't found a way yet to exclude the tests which depend on python based on whether the script succeeded.
